### ISSUE TITLE
Failed to load the global-background package

### ISSUE THREAD

**Issue by ynhhoJ** [simon-xia/atom-global-background#3]
Duplicate key 'ctrl-alt-g'
Hide Stack Trace
Error: Duplicate key 'ctrl-alt-g'
  at Object.detectDuplicateKeys (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\season\lib\cson.js:268:13)
  at C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\cson-parser\lib\parse.js:115:38
  at Array.reduce (native)
  at Obj (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\cson-parser\lib\parse.js:107:30)
  at transformNode (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\cson-parser\lib\parse.js:197:12)
  at Value (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\cson-parser\lib\parse.js:79:14)
  at transformNode (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\cson-parser\lib\parse.js:197:12)
  at C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\cson-parser\lib\parse.js:114:17
  at Array.reduce (native)
  at Obj (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\cson-parser\lib\parse.js:107:30)
  at transformNode (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\cson-parser\lib\parse.js:197:12)
  at Value (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\cson-parser\lib\parse.js:79:14)
  at transformNode (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\cson-parser\lib\parse.js:197:12)
  at Block (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\cson-parser\lib\parse.js:76:14)
  at transformNode (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\cson-parser\lib\parse.js:197:12)
  at Object.parse (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\cson-parser\lib\parse.js:203:12)
  at parseObject (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\season\lib\cson.js:42:23)
  at parseContentsSync (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\season\lib\cson.js:68:16)
  at Object.readFileSync (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\season\lib\cson.js:170:14)
  at C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\src\package.js:387:38
  at Array.map (native)
  at Package.module.exports.Package.loadKeymaps (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\src\package.js:384:46)
  at C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\src\package.js:110:19
  at Package.module.exports.Package.measure (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\src\package.js:92:15)
  at Package.module.exports.Package.load (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\src\package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\src\package-manager.js:466:14)
  at C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\src\package-manager.js:410:19
  at Config.module.exports.Config.transact (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\src\config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\src\package-manager.js:405:19)
  at C:\Users\lJohh\AppData\Local\atom\app-1.12.5\resources\app.asar\src\atom-environment.js:772:28

**Comment by jweboy** [comment]
I have encountered the same problem, there is a solution?

**Comment by simon-xia** [comment]
it's because other plugin use `ctrl-alt-g` as hot key,  disable it or comment mine [https://github.com/simon-xia/atom-global-background/blob/master/keymaps/global-background.cson#L11-L13](https://github.com/simon-xia/atom-global-background/blob/master/keymaps/global-background.cson#L11-L13)

**Comment by ynhhoJ** [comment]
Thanks, its works.
I deleted hotkey.

**Comment by ccqgithub** [comment]
@lJohhnyl @simon-xia  how to comment it in this plugin ?

**Comment by yyyyuuu** [comment]
@simon-xia 
it's not because other plugin use `ctrl-alt-g `,the question is caused by the duplicate  in your  global-background.cson ,there are two same key `ctrl-alt-g` in the  global-background.cson ,after changing one of it to another key(  `ctrl-alt-r` ),the plugin will work properly.

**Comment by simon-xia** [comment]
thanks @yyyyuuu , it is another way to fix this

**Comment by slanterns** [comment]
@yyyyuuu @simon-xia It works.Thanks!

**Comment by laricoDGT** [comment]
where is located   global-background.cson file? for edit

**Comment by simon-xia** [comment]
@laricoDGT  under dir `keymaps`
