### ISSUE TITLE
Failed to activate the global-background package

### ISSUE THREAD

**Issue by LLNAN** [simon-xia/atom-global-background#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0-beta4 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [global-background](https://github.com/simon-xia/atom-global-background) package 0.4.0

### Stack Trace

Failed to activate the global-background package

```
At Cannot find module 'request'

Error: Cannot find module 'request'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (~/AppData/Local/atom/app-1.17.0-beta4/resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.get_Module._resolveFilename (<embedded>:7991:58)
  at Module.require (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/static/index.js:40:43)
  at require (<embedded>:7345:33)
  at /packages/atom-global-background-master/lib/global-background-view.coffee:2:11)
  at /packages/atom-global-background-master/lib/global-background-view.coffee:1:1)
  at Module.get_Module._compile (<embedded>:7385:36)
  at Object.value [as .coffee] (<embedded>:7627:29)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/static/index.js:47:45)
  at require (<embedded>:7345:33)
  at /packages/atom-global-background-master/lib/global-background.coffee:1:24)
  at /packages/atom-global-background-master/lib/global-background.coffee:1:1)
  at Module.get_Module._compile (<embedded>:7385:36)
  at Object.value [as .coffee] (<embedded>:7627:29)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (~/AppData/Local/atom/app-1.17.0-beta4/resources/app/static/index.js:47:45)
  at require (internal/module.js:20:19)
  at customRequire (<embedded>:73:

**Comment by lod61** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [global-background](https://github.com/simon-xia/atom-global-background) package 0.4.0


### Stack Trace

Failed to activate the global-background package

```
At EISDIR: illegal operation on a directory, read

Error: EISDIR: illegal operation on a directory, read
  at Error (native)
  at Object.fs.readSync (fs.js:731:19)
  at tryReadSync (fs.js:486:20)
  at Object.fs.readFileSync (fs.js:534:19)
  at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
  at GlobalBackgroundView.fetchImageFromFile (/packages/global-background/lib/global-background-view.coffee:75:19)
  at /packages/global-background/lib/global-background-view.coffee:37:14)
  at Object.activate (/packages/global-background/lib/global-background.coffee:11:33)
  at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
  at /app.asar/src/package.js:190:32
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at /app.asar/src/package.js:183:26
  at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
  at /app.asar/src/package-manager.js:531:29
  at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
  at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
  at /app.asar/src/atom-environment.js:826:28

```

### Commands

```
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.29.18 
atom-clock 0.1.6 
atom-material-ui 1.3.9 
atom-minify 0.8.0 
atom-ternjs 0.18.2 
autocomplete 0.47.0 
autocomplete-angular-material 0.4.0 
autocomplete-paths 1.0.5 
busy-signal 1.3.0 
emmet 2.4.3 
encourage 0.4.0 
file-icons 2.1.3 
global-background 0.4.0 
highlight-line 0.12.0 
intentions 1.1.2 
jshint 1.8.6 
language-vue 0.21.2 
language-vue-component 0.5.0 
linter 2.1.2 
linter-jshint 3.0.3 
linter-ui-default 1.2.2 
markdown-preview-plus 2.4.9 
minimap 4.27.1 
open-in-browsers 0.0.19 
sass-autocompile 0.13.3 
vue-autocompile 0.0.6 
vue-autocomplete 0.1.1 
vue-element-ui-snippets 0.7.0 
vue-format 0.4.0 
vue-snippets 0.6.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by lod61** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [global-background](https://github.com/simon-xia/atom-global-background) package 0.4.0


### Stack Trace

Failed to load the global-background package

```
At Duplicate key 'ctrl-alt-g'

Error: Duplicate key 'ctrl-alt-g'
  at Object.detectDuplicateKeys (/app.asar/node_modules/season/lib/cson.js:268:13)
  at /app.asar/node_modules/cson-parser/lib/parse.js:115:38
  at Array.reduce (native)
  at Obj (/app.asar/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Value (/app.asar/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at /app.asar/node_modules/cson-parser/lib/parse.js:114:17
  at Array.reduce (native)
  at Obj (/app.asar/node_modules/cson-parser/lib/parse.js:107:30)
  at transformNode (/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Value (/app.asar/node_modules/cson-parser/lib/parse.js:79:14)
  at transformNode (/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Block (/app.asar/node_modules/cson-parser/lib/parse.js:76:14)
  at transformNode (/app.asar/node_modules/cson-parser/lib/parse.js:197:12)
  at Object.parse (/app.asar/node_modules/cson-parser/lib/parse.js:203:12)
  at parseObject (/app.asar/node_modules/season/lib/cson.js:42:23)
  at parseContentsSync (/app.asar/node_modules/season/lib/cson.js:68:16)
  at Object.readFileSync (/app.asar/node_modules/season/lib/cson.js:170:14)
  at /app.asar/src/package.js:439:38
  at Array.map (native)
  at Package.module.exports.Package.loadKeymaps (/app.asar/src/package.js:436:46)
  at /app.asar/src/package.js:114:19
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
  at /app.asar/src/package-manager.js:412:19
  at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
  at /app.asar/src/atom-environment.js:792:28

```

### Commands

```
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.29.18 
atom-clock 0.1.6 
atom-material-ui 1.3.9 
atom-minify 0.8.0 
atom-ternjs 0.18.2 
autocomplete 0.47.0 
autocomplete-angular-material 0.4.0 
autocomplete-paths 1.0.5 
busy-signal 1.3.0 
emmet 2.4.3 
encourage 0.4.0 
file-icons 2.1.3 
global-background 0.4.0 
highlight-line 0.12.0 
intentions 1.1.2 
jshint 1.8.6 
language-vue 0.21.2 
language-vue-component 0.5.0 
linter 2.1.2 
linter-jshint 3.0.3 
linter-ui-default 1.2.2 
markdown-preview-plus 2.4.9 
minimap 4.27.1 
open-in-browsers 0.0.19 
sass-autocompile 0.13.3 
vue-autocompile 0.0.6 
vue-autocomplete 0.1.1 
vue-element-ui-snippets 0.7.0 
vue-format 0.4.0 
vue-snippets 0.6.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by lod61** [comment]
你好，这个看起来很酷炫，但是怎么使用啊？ 我设置了本地的图片路径之后没反应还报了上述错误。网络图片链接地址也无效。

**Comment by edo-zhou** [comment]
../bg.png

**Comment by edo-zhou** [comment]
路径是相对配置文件的路径。配置文件在atom／package／global-background／lib下。将pic放在atom／package／global-background下  ../pic.png
